// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/_404.tsx";
import * as $1 from "./routes/_500.tsx";
import * as $2 from "./routes/api/joke.ts";
import * as $3 from "./routes/api/login.ts";
import * as $4 from "./routes/api/logout.ts";
import * as $5 from "./routes/app/[name].tsx";
import * as $6 from "./routes/app/_middleware.ts";
import * as $7 from "./routes/app/dashboard.tsx";
import * as $8 from "./routes/index.tsx";
import * as $9 from "./routes/test.tsx";
import * as $$0 from "./islands/Countdown.tsx";
import * as $$1 from "./islands/Counter.tsx";

const manifest = {
  routes: {
    "./routes/_404.tsx": $0,
    "./routes/_500.tsx": $1,
    "./routes/api/joke.ts": $2,
    "./routes/api/login.ts": $3,
    "./routes/api/logout.ts": $4,
    "./routes/app/[name].tsx": $5,
    "./routes/app/_middleware.ts": $6,
    "./routes/app/dashboard.tsx": $7,
    "./routes/index.tsx": $8,
    "./routes/test.tsx": $9,
  },
  islands: {
    "./islands/Countdown.tsx": $$0,
    "./islands/Counter.tsx": $$1,
  },
  baseUrl: import.meta.url,
};

export default manifest;
