import { ResourceLoader } from "../helpers/loader.ts";
import * as postgres from "$postgres";
import * as supabase from "supabase";

export interface DatabaseUser {
  userId: number;
  userName: string;
  avatarUrl: string;
}

export class Database {
  #client: supabase.SupabaseClient;

  constructor(client?: supabase.SupabaseClient) {
    this.#client = client ?? supabase.createClient(
      Deno.env.get("SUPABASE_API_URL")!,
      Deno.env.get("SUPABASE_ANON_KEY")!,
    );
  }

  async insertUser(user: DatabaseUser & { accessToken: string }) {
    const { error } = await this.#client
      .from("users")
      .upsert([
        {
          provider_id: user.userId,
          username: user.userName,
          avatar_url: user.avatarUrl,
          access_token: user.accessToken,
        },
      ], { returning: "minimal" });
    if (error) {
      throw new Error(error.message);
    }
  }

  async getUserByAccessTokenOrThrow(
    accessToken: string,
  ): Promise<DatabaseUser> {
    const user = await this.getUserByAccessToken(accessToken);
    if (user == null) {
      throw new Error("Could not find user with access token.");
    }
    return user;
  }

  async getUserByAccessToken(
    accessToken: string,
  ): Promise<DatabaseUser | undefined> {
    const { data, error } = await this.#client
      .from("users")
      .select("id,username,avatar_url")
      .eq("access_token", accessToken);
    if (error) {
      throw new Error(error.message);
    }
    if (data.length === 0) {
      return undefined;
    }
    return {
      userId: data[0].id,
      userName: data[0].username,
      avatarUrl: data[0].avatar_url,
    };
  }

  async getRooms() {
    const { data, error } = await this.#client.from("rooms_with_activity")
      .select(
        "id,name,last_message_at",
      );
    if (error) {
      throw new Error(error.message);
    }
    return data.map((d) => ({
      roomId: d.id,
      name: d.name,
      lastMessageAt: d.last_message_at,
    }));
  }
}

export const databaseLoader = new ResourceLoader<Database>({
  async load() {
    // automatically create the database schema on startup
    const client = new postgres.Client({
      hostname: getEnvOrThrow("SUPABASE_DB_HOSTNAME"),
      port: Deno.env.get("SUPABASE_DB_PORT") ?? 5432,
      user: Deno.env.get("SUPABASE_DB_USER") ?? "postgres",
      password: getEnvOrThrow("SUPABASE_DB_PASSWORD"),
      database: Deno.env.get("SUPABASE_DB_NAME") ?? "postgres",
    });
    await client.connect();
    await client.queryArray(`
         create table if not exists users (
           id integer generated by default as identity primary key,
           provider_id numeric unique not null,
           created_at timestamp with time zone default timezone('utc'::text, now()) not null,
           username text unique,
           avatar_url text,
           access_token text
         );
   `);
    await client.end();
    return Promise.resolve(new Database());

    function getEnvOrThrow(name: string) {
      const value = Deno.env.get(name);
      if (value == null) {
        throw new Error(`Missing env variable: ${name}`);
      }
      return value;
    }
  },
});
